site_name: NC2-Lab
site_url: https://github.com/bhgoh/nc2-lab.git

# Copyright
copyright: Copyright &copy; 2016 - 2025 Nutanix

nav:
- Home: index.md

# Migrate to Nutanix

- Migrate to Nutanix: 
  - Migrate/overview.md
  - Lab Environment: Migrate/lab env.md

- Setting up the Environment:
  - SetEnv/overview.md                    
  - SetEnv/categoryandpolicy.md
  - SetEnv/policy.md
  - SetEnv/playbook.md
  - SetEnv/setuptakeaway.md

- Migrating Workloads:
  - MigrateWLs/overview.md
  - MigrateWLs/setupmove.md
  - MigrateWLs/migratingvm.md
  - MigrateWLs/migrateplan.md
  - MigrateWLs/migratevm.md

- Advanced VM Migration:
  - AdvMigrate/advancedmigrate.md
  - AdvMigrate/expadvplan.md
  - AdvMigrate/migratevm.md
  - AdvMigrate/migratescale.md
  - AdvMigrate/migratetakeaway.md

- Day Two Management:
  - Day2/overview.md
  - Day2/ngt.md
  - Day2/iam.md
  - Day2/reports.md
  - Day2/capacityp.md
  - Day2/vmdetect.md
  - Day2/keytakeaways.md

- Disaster Recovery:
  - DR/overview.md 
  - DR/clustersetup.md
  - DR/pp.md  
  - DR/rp.md  
  - DR/testp.md  
  - DR/takeaway.md  

theme:
  logo: assets/ntnx.png
  # Configuration
  palette:
  #   - primary: deep purple
  #   - accent: black

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.footer
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    #- content.tabs.link

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.tabbed:
    alternate_style: true
- attr_list
- md_in_html
- pymdownx.keys
- pymdownx.magiclink


